version: '3.8'

services:
   music-app:
     container_name: music-app
     restart: always
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 3001:80

     networks:
       - music-app_network

networks:
  music-app_network:
    driver: bridge
